/* 
1. Dummy Text Generate.
2. Selecting Element.
3. Event Listener.
*/

// Dummy Text Generate.
const dummyText = [
    'Soufflé gingerbread jujubes apple pie. Danish icing pastry chocolate cake marzipan croissant brownie. Cotton candy sugar plum tiramisu oat cake cookie ice cream danish oat cake candy canes. Soufflé sesame snaps sweet roll tootsie roll. Apple pie lemon drops dessert. Pastry macaroon chupa chups marshmallow bear claw sweet roll cupcake.',
    'Powder liquorice brownie fruitcake candy canes macaroon. Toffee wafer wafer oat cake cake sweet. Caramels jelly beans jujubes sweet roll cookie oat cake cake bear claw tiramisu. Sesame snaps fruitcake gingerbread gummies halvah chocolate apple pie cupcake. Bonbon soufflé ice cream carrot cake chocolate cake pastry gingerbread. Pudding gummi bears pastry chocolate dragée. Cheesecake biscuit sesame snaps candy. Wafer cheesecake bear claw biscuit macaroon jelly jelly-o. Jujubes apple pie halvah. Gingerbread jelly beans jelly-o liquorice chocolate cake candy pudding tart.',
    'Jelly-o gingerbread halvah icing. Soufflé ice cream sweet roll muffin danish bear claw jelly beans chocolate cake. Muffin liquorice caramels jelly. Macaroon caramels macaroon. Cheesecake tiramisu danish brownie pastry candy canes cotton candy jujubes dessert. Chupa chups donut gummies sweet roll. Tootsie roll halvah cotton candy danish jelly-o sesame snaps marzipan croissant. Cake chocolate bar tart bear claw gummies. Chupa chups biscuit pie cheesecake candy canes halvah lemon drops jelly. Tiramisu cheesecake cheesecake sesame snaps jelly beans marzipan cheesecake biscuit.',
    'Gummies gingerbread macaroon dragée. Danish marshmallow jelly chocolate cake carrot cake tart. Sesame snaps donut bonbon wafer. Cake toffee sugar plum chocolate gummies tootsie roll. Sweet icing sweet roll dessert ice cream sweet roll sugar plum tart. Cake liquorice pastry chocolate cake dragée gummies. Topping sesame snaps chocolate bar macaroon jelly-o carrot cake tootsie roll toffee halvah. Jujubes apple pie sesame snaps. Brownie ice cream jujubes chocolate cake sweet lollipop lemon drops cupcake. Cake croissant tiramisu topping dessert.',
    'Apple pie sweet liquorice tart gingerbread halvah chupa chups jelly lollipop. Jelly beans candy canes topping lollipop marzipan chocolate bar wafer gingerbread. Fruitcake sesame snaps carrot cake cookie chupa chups tootsie roll wafer cake bear claw. Cake tart ice cream pie. Oat cake sesame snaps jelly-o ice cream soufflé gummies candy canes. Pastry marshmallow macaroon croissant. Candy canes marzipan pudding. Sesame snaps cake pudding sweet roll dragée. Chupa chups tootsie roll marshmallow.',
    'Candy canes cake caramels muffin wafer bear claw. Soufflé ice cream danish fruitcake pudding cookie sesame snaps muffin. Sweet roll pastry tart toffee toffee sesame snaps dragée candy lollipop. Croissant jelly-o jelly-o jujubes lemon drops jelly chocolate cake. Toffee cookie sugar plum marshmallow jujubes lemon drops chupa chups. Halvah gummies brownie sweet roll icing cookie. Sugar plum biscuit pastry carrot cake icing oat cake cake donut candy. Cotton candy cake macaroon jujubes muffin. Macaroon oat cake cupcake jelly-o apple pie.',
    'Cotton candy brownie danish apple pie sweet roll cotton candy oat cake cake liquorice. Sweet roll pastry jelly beans pudding candy cheesecake. Halvah chupa chups jujubes danish gummi bears jelly dessert. Brownie gummi bears jelly-o candy canes. Gummies jelly beans jelly beans fruitcake candy canes donut fruitcake. Chocolate bar chocolate cake sesame snaps marshmallow gummies icing topping carrot cake tootsie roll.',
    'Cake cotton candy jelly-o dessert wafer jelly cupcake. Marshmallow jelly beans powder jujubes tart marzipan macaroon bear claw. Tart carrot cake croissant biscuit danish sugar plum dessert. Toffee tart jelly beans bonbon chocolate cake halvah. Cake dessert pastry liquorice. Tart chocolate bar jelly muffin bonbon. Jelly beans apple pie topping gummi bears. Fruitcake croissant sesame snaps muffin. Icing chupa chups bonbon jujubes macaroon icing jelly macaroon. Chocolate bar halvah marzipan cake cake.',
    'Bear claw dragée gummies liquorice jelly beans sugar plum soufflé. Danish gummies soufflé. Carrot cake cake sweet roll danish danish candy canes lemon drops cupcake. Jujubes bear claw soufflé croissant. Croissant gingerbread halvah. Candy cupcake sugar plum ice cream wafer donut pie cheesecake.',
    'Caramels gummies caramels. Jelly-o jelly chocolate cake chocolate bar cotton candy soufflé. Jelly-o jelly jujubes cake dessert. Jelly beans cotton candy jelly beans chocolate apple pie donut ice cream fruitcake jelly-o. Sugar plum icing cake gummies carrot cake bear claw marshmallow. Gummies tootsie roll bonbon cotton candy cookie marzipan topping marshmallow. Halvah bonbon sugar plum wafer chocolate wafer brownie fruitcake.',
    'Cake icing danish cake muffin carrot cake halvah bonbon gingerbread. Pudding soufflé oat cake chupa chups jelly candy. Gingerbread lemon drops cake toffee dessert macaroon gummies dessert tiramisu. Soufflé donut halvah soufflé bonbon muffin biscuit. Croissant marshmallow candy cheesecake cake chupa chups cake. Cotton candy danish jelly icing liquorice jelly-o gummi bears bear claw biscuit. Apple pie apple pie dragée danish soufflé chocolate cake dragée macaroon.',
    'Candy canes bear claw cupcake. Pie oat cake muffin oat cake lemon drops gummies jujubes. Icing gummies pie topping. Chupa chups powder danish apple pie cupcake soufflé dragée oat cake. Cake carrot cake donut lemon drops ice cream apple pie chocolate tootsie roll. Gummi bears sweet tart jelly beans.',
    'Jelly jelly dragée. Topping cotton candy bear claw tootsie roll ice cream croissant cookie lollipop gummies. Liquorice danish cake donut chocolate sugar plum macaroon sesame snaps. Jelly-o carrot cake chocolate bar liquorice jelly pastry chocolate cake. Bear claw topping donut. Pastry donut danish cupcake pastry dragée carrot cake pie sweet. Caramels macaroon cake.',
    'Oat cake jelly-o jelly cupcake ice cream dessert chocolate cake cake. Gingerbread gingerbread topping halvah dessert soufflé muffin chocolate bar cheesecake. Tiramisu powder chocolate cake lollipop sugar plum. Liquorice muffin apple pie sweet macaroon. Cheesecake pie fruitcake cookie carrot cake sugar plum ice cream. Pie chupa chups brownie gingerbread ice cream. Muffin sugar plum tart tart tiramisu cake marzipan sweet candy canes. Dragée bear claw cotton candy croissant bear claw danish danish gingerbread gingerbread. Lollipop tiramisu gummies cake cookie lollipop soufflé.',
    'Wafer fruitcake gingerbread gummies gingerbread tart soufflé bear claw. Pudding liquorice caramels lemon drops cotton candy. Chocolate macaroon bear claw. Donut cheesecake macaroon. Candy soufflé dragée. Oat cake carrot cake cookie.',
    'Marshmallow liquorice halvah sweet croissant. Caramels carrot cake oat cake cookie pie tootsie roll. Jujubes bonbon chocolate cake lollipop sesame snaps. Tootsie roll marzipan bonbon soufflé chocolate cake tart sesame snaps sesame snaps danish. Jelly beans croissant cotton candy bear claw jelly beans liquorice jelly-o ice cream. Tiramisu pudding cotton candy. Fruitcake lemon drops sweet roll chupa chups topping marzipan. Jelly-o ice cream biscuit.',
    'Pudding cupcake tootsie roll toffee cake chocolate chupa chups danish. Tart jelly-o oat cake candy bonbon. Powder gummies candy pastry gingerbread sweet roll. Sweet roll macaroon bear claw cheesecake muffin pastry. Gummi bears tootsie roll tootsie roll gummi bears tiramisu. Cheesecake powder gummies carrot cake. Jelly-o bonbon cake. Tart caramels cake sesame snaps tootsie roll lemon drops croissant cheesecake. Sugar plum ice cream danish sesame snaps bonbon pudding sesame snaps cupcake wafer.',
    'Biscuit sesame snaps sweet cake cake ice cream ice cream liquorice. Toffee tart tiramisu chupa chups lollipop gummies. Carrot cake donut pudding lemon drops. Sweet tootsie roll bonbon jujubes carrot cake croissant danish. Tart chocolate cake lollipop tart. Soufflé ice cream sweet roll dragée pastry topping chupa chups donut. Carrot cake bear claw lollipop jelly-o.',
    'Cake fruitcake lollipop. Tootsie roll lemon drops gummi bears liquorice. Chocolate marzipan sesame snaps bear claw cotton candy. Cake macaroon chocolate. Carrot cake biscuit marshmallow. Candy gummi bears gummi bears topping chocolate bar oat cake. Tiramisu croissant ice cream sesame snaps cheesecake bonbon bear claw muffin macaroon. Dessert liquorice muffin fruitcake lemon drops ice cream dessert. Sugar plum topping biscuit toffee cake dragée cake. Cotton candy pudding gummies.',
    'Candy canes pastry lollipop muffin liquorice. Chocolate lollipop wafer. Wafer biscuit gummi bears candy canes cotton candy candy apple pie. Ice cream powder icing jelly-o gingerbread carrot cake. Caramels macaroon carrot cake cheesecake bear claw carrot cake lemon drops cupcake dragée. Toffee soufflé macaroon tootsie roll apple pie icing. Caramels chupa chups pudding lemon drops oat cake pastry muffin apple pie muffin. Cotton candy cake icing cotton candy chocolate cake marshmallow tiramisu croissant toffee. Jelly-o carrot cake biscuit.',
    'Macaroon chupa chups cheesecake tootsie roll. Ice cream cake sugar plum candy tiramisu gingerbread pastry biscuit apple pie. Gummies muffin dragée lemon drops chocolate. Dessert pastry chocolate dragée cookie. Macaroon sweet roll cupcake caramels cookie. Pudding jelly beans halvah. Donut bear claw sugar plum marzipan.',
    'Halvah liquorice muffin ice cream marzipan toffee halvah sweet roll. Cupcake gingerbread gummi bears candy canes donut cupcake dessert apple pie. Icing chocolate cake pudding tart lollipop jelly beans. Chocolate cake cupcake powder powder tart brownie. Cookie tart sweet roll candy dessert cotton candy gingerbread. Tootsie roll jujubes cupcake cotton candy carrot cake. Sweet halvah tiramisu bear claw icing cookie chocolate cake jelly. Caramels chocolate chocolate bar apple pie fruitcake sweet marzipan toffee carrot cake. Tart dragée jujubes.',
    'Ice cream wafer muffin. Topping bear claw chupa chups liquorice fruitcake. Chocolate cake cake pastry donut jujubes caramels tootsie roll bear claw. Tart sugar plum icing biscuit jujubes croissant pie tiramisu. Icing cookie bear claw cake cookie. Brownie pastry dessert cupcake tiramisu candy canes tootsie roll chocolate cake croissant. Bear claw brownie gummi bears fruitcake icing. Jelly-o muffin biscuit cookie bonbon muffin jelly lollipop. Powder pudding macaroon halvah. Biscuit liquorice liquorice cake jelly-o.',
    'Candy cheesecake chupa chups gummi bears toffee candy canes. Gummies donut liquorice cookie brownie sugar plum. Apple pie bear claw biscuit jelly-o soufflé. Icing liquorice caramels pudding bonbon cookie sesame snaps caramels. Donut gingerbread chocolate cake caramels toffee. Tart tootsie roll sugar plum. Gingerbread tiramisu halvah jujubes.',
    'Tart danish macaroon cake pudding powder cake sugar plum. Sugar plum gingerbread pastry gummi bears chocolate cotton candy donut pastry. Jelly beans powder chupa chups jelly pudding candy topping. Chocolate muffin cake pudding cookie sugar plum chocolate bar jelly beans. Liquorice chupa chups chupa chups. Muffin bear claw macaroon muffin candy. Donut chocolate cake halvah lollipop tart chupa chups sugar plum.',
    'Cheesecake marzipan carrot cake fruitcake cotton candy. Powder powder tootsie roll cookie sugar plum tart dessert. Fruitcake dessert cotton candy muffin jujubes candy caramels candy canes cotton candy. Jelly beans cotton candy sesame snaps pie jelly. Candy macaroon cookie topping gingerbread candy canes liquorice apple pie. Cookie brownie jujubes donut pie sweet roll gummies. Danish danish candy croissant sweet marshmallow liquorice. Muffin cupcake toffee caramels dessert liquorice cake sesame snaps. Gummi bears donut jelly pie cookie gummies icing danish cupcake. Chupa chups cake toffee cotton candy pastry.',
    'Carrot cake cake cheesecake muffin. Jelly-o jelly icing cotton candy topping. Sweet roll cupcake sweet. Jujubes cotton candy icing bonbon gummi bears chocolate bar carrot cake. Donut caramels cookie cupcake gummi bears fruitcake danish muffin. Sesame snaps ice cream wafer croissant dessert jelly beans cheesecake. Icing jelly beans topping candy bonbon icing candy canes caramels. Pudding caramels apple pie chocolate wafer carrot cake liquorice. Sugar plum fruitcake lollipop chocolate bar pudding lollipop cupcake. Oat cake gummies croissant powder powder sugar plum donut candy canes muffin.',
    'Cupcake jelly beans jelly dessert candy. Sweet roll lollipop chocolate bar chocolate wafer oat cake marzipan. Chupa chups cake marshmallow lemon drops. Ice cream dessert macaroon. Liquorice muffin gingerbread chupa chups powder candy powder. Fruitcake donut macaroon wafer sesame snaps chupa chups. Gummi bears wafer sugar plum chocolate bar. Bear claw cotton candy halvah carrot cake danish. Sugar plum tart powder sweet candy. Liquorice sesame snaps sweet roll bonbon marshmallow.',
    'Muffin caramels candy jelly tootsie roll topping. Jelly beans brownie jelly beans chocolate bar tootsie roll candy canes oat cake gingerbread halvah. Oat cake muffin pie bonbon marzipan jujubes dessert powder. Donut chocolate apple pie cupcake marzipan. Bear claw cookie toffee bear claw brownie carrot cake. Tiramisu wafer cake topping biscuit tootsie roll cake wafer. Topping cake toffee marzipan biscuit jelly jelly beans cheesecake sugar plum. Danish bear claw wafer cotton candy marshmallow sugar plum tart. Powder icing cake topping carrot cake cookie. Tart jujubes caramels.',
    'Oat cake liquorice croissant tiramisu dessert fruitcake chocolate bar. Muffin gingerbread cookie. Jelly-o chocolate bar sesame snaps cake. Jelly-o chupa chups danish chupa chups cheesecake gingerbread oat cake. Biscuit jelly beans gingerbread jujubes lemon drops pastry dessert sesame snaps. Chocolate cake soufflé cookie gingerbread cake cupcake. Chocolate bar chupa chups chupa chups carrot cake ice cream. Cookie wafer candy biscuit apple pie sweet roll dragée cookie sweet. Macaroon biscuit gingerbread jujubes fruitcake cupcake. Chupa chups dessert tiramisu pastry oat cake cupcake danish.',
    'Macaroon cheesecake marzipan macaroon jelly beans. Lemon drops dragée bonbon fruitcake pie. Lemon drops sesame snaps cheesecake apple pie pudding candy jujubes gummi bears. Biscuit apple pie bonbon bonbon jelly beans carrot cake caramels chupa chups toffee. Danish sesame snaps apple pie jelly beans icing bonbon tart. Jelly beans donut jujubes cheesecake tiramisu halvah cheesecake donut apple pie. Topping liquorice chocolate pudding. Jelly beans liquorice jujubes.',
];


// Selecting Element.
const form = document.querySelector('#form');
const amount = document.querySelector('#amount');
const result = document.querySelector('#result');


//  Event Listener.
form.addEventListener('submit', function(e) {
    e.preventDefault();

    const value = parseInt(amount.value);
    const random = Math.floor(Math.random() * dummyText.length);

    // for empty, negatigve and greater than 31
    if (isNaN(value) || value <= 0 || value > 31) {
        result.innerHTML = `<p>${dummyText[random]}</p>`;
    } else {
        const slicedArray = dummyText.slice(0, value);
        const finalArray = slicedArray
            .map(function(singleDummy) {
                return `<p>${singleDummy}</p>`;
            })
            .join('');

        // displaying final dummy text
        result.innerHTML = finalArray;
    }
});